const DEFAULT=[{id:"MAT",name:"MAT",kind:"num",min:0,max:99},{id:"RelMat",name:"RelMat",kind:"quick",values:["1.5","1.7","1.9","2.1","2.5","2.9","3.1","3.5","3.9"],other:true},{id:"Lodging",name:"Lodging",kind:"quick",values:["1","2","3","4","5"]},{id:"Height",name:"Height",kind:"num",min:0,max:99}];
const ROLES=[["range","Plot Range / Range",1],["column","Plot Column / Column",1],["plot","Plot"],["entry","Entry"],["name","Name / Pedigree / Variety"],["experiment","Experiment"],["block","Block"],["uniqueid","Unique ID"],["type","Type / Border"],["fieldPlan","Field Plan"],["location","Location"]];
const STORE="fieldNotesPWA-v1";let DB=JSON.parse(localStorage.getItem(STORE)||"null")||{fields:{},current:null};let W,rows=[],heads=[],filename="";
const $=x=>document.getElementById(x),esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),persist=()=>localStorage.setItem(STORE,JSON.stringify(DB)),F=()=>DB.fields[DB.current]||null;
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>tab(b.dataset.tab));function tab(id){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.tab===id));if(id==="home")home();if(id==="notes")notes();if(id==="map")map();if(id==="backup")backup()}
function conn(){let x=$("connection");x.className="card "+(navigator.onLine?"online":"offline");x.innerHTML=navigator.onLine?"<b>Online</b> — app is available now. Imported fields and notes are stored locally.":"<b>✓ Offline</b> — fieldbooks and note taking remain available on this device."}window.addEventListener("online",conn);window.addEventListener("offline",conn);
function home(){conn();let d=$("fields");d.innerHTML="";let fs=Object.values(DB.fields);if(!fs.length)d.innerHTML='<p class="muted">No fields imported yet.</p>';fs.forEach(f=>{let done=f.plots.filter(p=>Object.keys(f.notes[key(p)]||{}).length).length,u=f.plots.filter(p=>!border(p)).length,x=document.createElement("div");x.className="fieldcard";x.innerHTML=`<div><h3>${esc(f.name)}</h3><div class="muted">${esc(f.info.location||"")} • ${done}/${u} plots noted</div></div><button class="primary">Open</button>`;x.querySelector("button").onclick=()=>{DB.current=f.id;persist();tab("notes")};d.appendChild(x)})}
$("file").onchange=async e=>{let f=e.target.files[0];if(!f)return;filename=f.name;try{W=XLSX.read(await f.arrayBuffer(),{type:"array"});$("sheet").innerHTML=W.SheetNames.map((n,i)=>`<option value="${i}">${esc(n)}</option>`).join("");$("sheetWrap").classList.toggle("hidden",W.SheetNames.length<2);loadSheet(0)}catch(e){msg("Could not read workbook: "+e.message)}};$("sheet").onchange=e=>loadSheet(+e.target.value);
function norm(s){return String(s).toLowerCase().replace(/[^a-z0-9]/g,"")}function guess(r){let A={range:["plotrange","range"],column:["plotcolumn","column","col"],plot:["plot","plotnumber"],entry:["entry"],name:["name1","name","pedigree","variety","genotype"],experiment:["experimentname","experiment","trial"],block:["block","rep"],uniqueid:["uniqueid","id"],type:["type","plottype"],fieldPlan:["fieldplan"],location:["location","site"]}[r]||[];return heads.findIndex(h=>A.includes(norm(h)))}
function loadSheet(i){let a=XLSX.utils.sheet_to_json(W.Sheets[W.SheetNames[i]],{header:1,defval:"",raw:false});heads=(a[0]||[]).map((x,i)=>String(x||`Column ${i+1}`).trim());rows=a.slice(1).filter(r=>r.some(v=>String(v).trim()));$("mapping").innerHTML="";ROLES.forEach(([r,l,q])=>{let g=guess(r),d=document.createElement("div");d.innerHTML=`<label>${l}${q?" *":""}</label><select id="m_${r}"><option value="-1">— not used —</option>${heads.map((h,i)=>`<option value="${i}" ${i===g?"selected":""}>${esc(h)}</option>`).join("")}</select>`;$("mapping").appendChild(d)});$("mappingCard").classList.remove("hidden");$("fieldSetup").classList.remove("hidden");$("fieldName").value=filename.replace(/\.(xlsx|xls|csv)$/i,"");}
function msg(s){$("importMsg").classList.remove("hidden");$("importMsg").textContent=s}
$("createField").onclick=()=>{try{let M={};ROLES.forEach(([r])=>M[r]=+$("m_"+r).value);if(M.range<0||M.column<0)throw Error("Range and Column are required.");let g=(a,r)=>M[r]>=0?a[M[r]]:"";let mapped=rows.map(a=>({range:Number(String(g(a,"range")).replace(/,/g,"").trim()),column:Number(String(g(a,"column")).replace(/,/g,"").trim()),plot:g(a,"plot"),entry:g(a,"entry"),name:g(a,"name"),experiment:g(a,"experiment"),block:g(a,"block"),uniqueid:g(a,"uniqueid"),type:g(a,"type"),fieldPlan:g(a,"fieldPlan"),location:g(a,"location"),raw:Object.fromEntries(heads.map((h,j)=>[h,a[j]??""]))}));let plots=mapped.filter(p=>Number.isFinite(p.range)&&Number.isFinite(p.column));let skipped=mapped.length-plots.length;if(!plots.length)throw Error("No usable rows found. Range and Column must be numeric.");let seen=new Set;for(let p of plots){if(seen.has(key(p)))throw Error("Duplicate Range/Column: "+key(p));seen.add(key(p))}let name=$("fieldName").value.trim()||filename,id="f-"+Date.now(),first=plots[0],f={id,name,heads,plots,notes:{},traits:JSON.parse(JSON.stringify(DEFAULT)),current:null,nav:$("defaultNav").value,info:{location:first.location||"",fieldPlan:first.fieldPlan||""},lastSave:null,collection:{experiments:[],reps:[]},travelDirection:"forward"};f.current=key(f.plots.find(p=>!border(p))||f.plots[0]);DB.fields[id]=f;DB.current=id;persist();msg(`✓ ${name} saved locally with ${plots.length} mapped rows${skipped?` (${skipped} non-plot/header rows skipped)`:""}. It is ready for offline note taking.`);tab("notes")}catch(e){msg(e.message)}};
function key(p){return p.range+"-"+p.column}function border(p){return String(p.type).toLowerCase().includes("border")}
function allUsable(f){return f.plots.filter(p=>!border(p))}
function repVal(p){return String(p.block??"").trim()||"Unassigned"}
function expVal(p){return String(p.experiment??"").trim()||"Unassigned"}
function usable(f){let a=allUsable(f),c=f.collection||{};if(c.experiments?.length)a=a.filter(p=>c.experiments.includes(expVal(p)));if(c.reps?.length)a=a.filter(p=>c.reps.includes(repVal(p)));return a}
function dict(f){return Object.fromEntries(f.plots.map(p=>[key(p),p]))}
function saveField(f){f.lastSave=new Date().toISOString();persist();$("saveStatus").textContent="✓ Saved locally • "+new Date().toLocaleTimeString();progress(f)}
function progress(f){let u=usable(f),n=u.filter(p=>Object.keys(f.notes[key(p)]||{}).length).length;$("progress").textContent=n+"/"+u.length+" plots"}
function baseOrder(f){let a=[...usable(f)];if(f.nav==="range-column")a.sort((x,y)=>x.range-y.range||x.column-y.column);else if(f.nav==="column-range")a.sort((x,y)=>x.column-y.column||x.range-y.range);else if(f.nav==="serpentine-column")a.sort((x,y)=>x.column-y.column||((x.column%2?1:-1)*(x.range-y.range)));else a.sort((x,y)=>x.range-y.range||((x.range%2?1:-1)*(x.column-y.column)));return a}
function order(f){let a=baseOrder(f);if((f.travelDirection||"forward")==="reverse")a.reverse();return a}
function notes(){let f=F();if(f&&!f.travelDirection)f.travelDirection="forward";$("noField").classList.toggle("hidden",!!f);$("notesUI").classList.toggle("hidden",!f);if(!f)return;let allowed=usable(f),cur=dict(f)[f.current],p=(cur&&allowed.some(x=>key(x)===key(cur)))?cur:allowed[0];if(!p){$("plotTitle").textContent="No plots match the current experiment/rep filter";$("coords").textContent="Change the Collection Filter on the Map tab.";return}let n=f.notes[key(p)]||{};f.current=key(p);$("plotTitle").textContent=p.plot!==""?"Plot "+p.plot:`Range ${p.range}, Column ${p.column}`;$("coords").textContent=`Range ${p.range} • Column ${p.column}${p.experiment?" • "+p.experiment:""}`;$("entry").textContent=p.name||p.type||"";$("meta").textContent=[p.entry!==""?"Entry "+p.entry:"",p.block!==""?"Block "+p.block:"",p.uniqueid?"ID "+p.uniqueid:""].filter(Boolean).join(" • ");$("navMode").value=f.nav;f.travelDirection=f.travelDirection||"forward";$("travelDirection").value=f.travelDirection;$("traits").innerHTML="";f.traits.forEach(t=>{let d=document.createElement("div");d.className="trait";d.innerHTML="<h3>"+esc(t.name)+"</h3>";if(t.kind==="quick"){let q=document.createElement("div");q.className="quick";t.values.forEach(v=>{let b=document.createElement("button");b.textContent=v;b.className=String(n[t.id]??"")===String(v)?"selected":"";b.onclick=()=>setNote(t.id,v);q.appendChild(b)});if(t.other){let b=document.createElement("button");b.textContent="Other";b.onclick=()=>{let v=prompt(t.name+":",n[t.id]??"");if(v!==null&&v!=="")setNote(t.id,v)};q.appendChild(b)}d.appendChild(q)}else{let i=document.createElement("input");i.type="number";i.inputMode="numeric";i.min=t.min??0;i.max=t.max??999;i.value=n[t.id]??"";i.onchange=()=>setNote(t.id,i.value);d.appendChild(i)};$("traits").appendChild(d)});progress(f)}
function setNote(id,v){let f=F();f.notes[f.current]??={};f.notes[f.current][id]=v;saveField(f);notes()}$("navMode").onchange=e=>{let f=F();if(f){f.nav=e.target.value;saveField(f)}};
$("travelDirection").onchange=e=>{let f=F();if(f){f.travelDirection=e.target.value;saveField(f);notes()}};
$("reverseNow").onclick=()=>{let f=F();if(!f)return;f.travelDirection=(f.travelDirection||"forward")==="forward"?"reverse":"forward";saveField(f);notes()};function move(d){let f=F(),a=order(f),i=a.findIndex(p=>key(p)===f.current);if(i<0||!a.length)return;let ni=i+d;if(ni<0||ni>=a.length)return;f.current=key(a[ni]);saveField(f);notes()}$("prev").onclick=()=>move(-1);$("next").onclick=()=>move(1);
$("addTrait").onclick=()=>{let f=F();if(!f)return;let n=prompt("Trait name:");if(!n)return;let t=prompt("Type: number, 1-5, or comma-separated buttons","number");if(!t)return;let id=n.replace(/\W/g,"_")+"_"+Date.now();f.traits.push(t==="1-5"?{id,name:n,kind:"quick",values:["1","2","3","4","5"]}:t.includes(",")?{id,name:n,kind:"quick",values:t.split(",").map(x=>x.trim()).filter(Boolean),other:true}:{id,name:n,kind:"num",min:0,max:999});saveField(f);notes()};
let mapZoom=1;
const EXP_COLORS=["#1565c0","#c62828","#6a1b9a","#ef6c00","#00838f","#558b2f","#ad1457","#4527a0","#2e7d32","#5d4037","#0277bd","#9e9d24"];
function expName(p){return String(p.experiment||"Unassigned")}
function expColorMap(f){let names=[...new Set(f.plots.filter(p=>!border(p)).map(expName))].sort();return Object.fromEntries(names.map((n,i)=>[n,EXP_COLORS[i%EXP_COLORS.length]]))}
function applyZoom(){let m=$("fieldmap");m.style.transform=`scale(${mapZoom})`;m.style.marginRight=((mapZoom-1)*m.scrollWidth)+"px";m.style.marginBottom=((mapZoom-1)*m.scrollHeight)+"px";$("zoomLabel").textContent=Math.round(mapZoom*100)+"%"}
function renderCollectionFilter(f){
f.collection=f.collection||{experiments:[],reps:[]};
let exps=[...new Set(allUsable(f).map(expVal))].sort(),reps=[...new Set(allUsable(f).map(repVal))].sort();
let ex=$("experimentFilter"),rp=$("repFilter");ex.className=rp.className="filterchecks";
ex.innerHTML=exps.map(v=>`<label><input type="checkbox" data-exp="${esc(v)}" ${!f.collection.experiments.length||f.collection.experiments.includes(v)?"checked":""}>${esc(v)}</label>`).join("");
rp.innerHTML=reps.map(v=>`<label><input type="checkbox" data-rep="${esc(v)}" ${!f.collection.reps.length||f.collection.reps.includes(v)?"checked":""}>${esc(v)}</label>`).join("");
let ce=f.collection.experiments?.length?f.collection.experiments.join(", "):"All experiments",cr=f.collection.reps?.length?f.collection.reps.join(", "):"All reps";$("filterSummary").textContent=`${ce} • Rep: ${cr} • ${usable(f).length} of ${allUsable(f).length} plots`;
}
function map(){let f=F(),m=$("fieldmap"),legend=$("expLegend");m.innerHTML="";legend.innerHTML="";if(!f){m.textContent="Choose a field first.";return}renderCollectionFilter(f);let allowedKeys=new Set(usable(f).map(key))
let colors=expColorMap(f);Object.entries(colors).forEach(([name,color])=>{let x=document.createElement("span");x.className="legenditem";x.innerHTML=`<i class="legendbox" style="border-color:${color}"></i>${esc(name)}`;legend.appendChild(x)});
let ps=f.plots,a=Math.min(...ps.map(p=>p.range)),b=Math.max(...ps.map(p=>p.range)),c=Math.min(...ps.map(p=>p.column)),d=Math.max(...ps.map(p=>p.column)),D=dict(f);
m.style.gridTemplateColumns=`repeat(${d-c+1},minmax(58px,1fr))`;
for(let r=b;r>=a;r--)for(let col=c;col<=d;col++){let p=D[r+"-"+col],x=document.createElement("div");x.className="cell";if(!p)x.style.visibility="hidden";else{
if(border(p))x.classList.add("border");else{x.classList.add("expborder");x.style.borderColor=colors[expName(p)]}
if(Object.keys(f.notes[key(p)]||{}).length)x.classList.add("noted");
if(!border(p)&&!allowedKeys.has(key(p)))x.classList.add("excluded");if(key(p)===f.current){x.classList.add("current");x.id="currentPlotCell"}
x.innerHTML=`<b>R${r} C${col}</b><br>${esc(p.plot)} ${esc(p.name||p.type)}`;
if(!border(p))x.onclick=()=>{if(!allowedKeys.has(key(p))){alert("This plot is outside the current Experiment / Rep collection filter. Select its experiment/rep above first.");return}f.current=key(p);saveField(f);tab("notes")}}m.appendChild(x)}
applyZoom()}
function fitMap(){let vp=$("mapViewport"),m=$("fieldmap");mapZoom=1;applyZoom();requestAnimationFrame(()=>{let available=vp.clientWidth-4,needed=m.scrollWidth;if(needed>0)mapZoom=Math.max(.35,Math.min(1,available/needed));applyZoom();vp.scrollTo(0,0)})}
function centerCurrent(){let c=$("currentPlotCell"),vp=$("mapViewport");if(!c)return;c.scrollIntoView({behavior:"smooth",block:"center",inline:"center"})}
function info(){let f=F(),d=$("infoForm");d.innerHTML="";if(!f){d.textContent="Choose a field first.";return}let fields=[["name","Field",f.name],["location","Location",f.info.location],["plantingDate","Planting Date",f.info.plantingDate],["fieldPlan","Field Plan",f.info.fieldPlan],["plots","Mapped Rows",f.plots.length],["usable","Note-taking Plots",usable(f).length]];fields.forEach(([k,l,v])=>{let x=document.createElement("div");x.innerHTML=`<label>${l}</label><div>${esc(v||"—")}</div>`;d.appendChild(x)})}
function dl(blob,name){let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function backup(){let f=F();$("backupStatus").textContent=f?(f.lastSave?"Last local save: "+new Date(f.lastSave).toLocaleString():"No notes saved yet."):"Choose a field first."}
$("backupFile").onclick=()=>{let f=F();if(!f)return;dl(new Blob([JSON.stringify({version:1,field:f},null,2)],{type:"application/json"}),f.name.replace(/\W+/g,"-")+"-FULL-BACKUP.json")};
$("restoreBtn").onclick=()=>$("restoreFile").click();$("restoreFile").onchange=async e=>{try{let b=JSON.parse(await e.target.files[0].text()),f=b.field;if(!f?.id||!Array.isArray(f.plots))throw Error();f.notes=f.notes||{};f.traits=f.traits?.length?f.traits:JSON.parse(JSON.stringify(DEFAULT));f.collection=f.collection||{experiments:[],reps:[]};f.travelDirection=f.travelDirection||"forward";f.nav=f.nav||"serpentine-range";f.info=f.info||{};f.heads=f.heads||Object.keys(f.plots[0]?.raw||{});f.current=f.current||key(f.plots.find(p=>!border(p))||f.plots[0]);DB.fields[f.id]=f;DB.current=f.id;persist();alert("Field and notes restored.");tab("notes")}catch(e){alert("Could not restore that backup.")}};
$("exportXlsx").onclick=()=>{let f=F();if(!f)return;let traitNames=f.traits.map(t=>t.name),allHeads=[...f.heads,...traitNames],rows=f.plots.map(p=>({...p.raw,...Object.fromEntries(f.traits.map(t=>[t.name,(f.notes[key(p)]||{})[t.id]??""]))})),ws=XLSX.utils.json_to_sheet(rows,{header:allHeads}),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Field Notes");XLSX.writeFile(wb,f.name.replace(/\W+/g,"-")+"-completed.xlsx")};
$("deleteField").onclick=()=>{let f=F();if(f&&confirm("Delete "+f.name+" and all its locally saved notes from this device?")){delete DB.fields[f.id];DB.current=null;persist();tab("home")}};
let deferred;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;$("install").classList.remove("hidden")});$("install").onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$("install").classList.add("hidden")}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");home();
$("zoomIn").onclick=()=>{mapZoom=Math.min(2.5,mapZoom+.15);applyZoom()};
$("zoomOut").onclick=()=>{mapZoom=Math.max(.35,mapZoom-.15);applyZoom()};
$("fitMap").onclick=fitMap;
$("centerCurrent").onclick=centerCurrent;
let pinchStart=null,pinchZoom=null;
$("mapViewport").addEventListener("touchstart",e=>{if(e.touches.length===2){let a=e.touches[0],b=e.touches[1];pinchStart=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);pinchZoom=mapZoom}},{passive:true});
$("mapViewport").addEventListener("touchmove",e=>{if(e.touches.length===2&&pinchStart){let a=e.touches[0],b=e.touches[1],d=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);mapZoom=Math.max(.35,Math.min(2.5,pinchZoom*d/pinchStart));applyZoom()}},{passive:true});
$("mapViewport").addEventListener("touchend",e=>{if(e.touches.length<2){pinchStart=null;pinchZoom=null}},{passive:true});

$("selectAllExp").onclick=()=>document.querySelectorAll("#experimentFilter input").forEach(x=>x.checked=true);
$("selectAllRep").onclick=()=>document.querySelectorAll("#repFilter input").forEach(x=>x.checked=true);
$("applyFilter").onclick=()=>{let f=F();if(!f)return;let allE=[...document.querySelectorAll("#experimentFilter input")],allR=[...document.querySelectorAll("#repFilter input")],selE=allE.filter(x=>x.checked).map(x=>x.dataset.exp),selR=allR.filter(x=>x.checked).map(x=>x.dataset.rep);if(!selE.length||!selR.length){alert("Select at least one Experiment and one Rep.");return}f.collection.experiments=selE.length===allE.length?[]:selE;f.collection.reps=selR.length===allR.length?[]:selR;let a=usable(f);if(!a.length){alert("No plots match that Experiment / Rep combination.");return}if(!a.some(p=>key(p)===f.current))f.current=key(a[0]);saveField(f);map();};
